Update remaining boilerplate to latest version.

diff --git a/git-nest b/git-nest
--- a/git-nest
+++ b/git-nest
@@ -35,6 +35,108 @@
 # --------------------------------------------------------------- end dev notes
 
 ###############################################################################
+# Strict Mode
+###############################################################################
+
+# Treat unset variables and parameters other than the special parameters ‘@’ or
+# ‘*’ as an error when performing parameter expansion. An 'unbound variable'
+# error message will be written to the standard error, and a non-interactive
+# shell will exit.
+#
+# This requires using parameter expansion to test for unset variables.
+#
+# http://www.gnu.org/software/bash/manual/bashref.html#Shell-Parameter-Expansion
+#
+# The two approaches that are probably the most appropriate are:
+#
+# ${parameter:-word}
+#   If parameter is unset or null, the expansion of word is substituted.
+#   Otherwise, the value of parameter is substituted. In other words, "word"
+#   acts as a default value when the value of "$parameter" is blank. If "word"
+#   is not present, then the default is blank (essentially an empty string).
+#
+# ${parameter:?word}
+#   If parameter is null or unset, the expansion of word (or a message to that
+#   effect if word is not present) is written to the standard error and the
+#   shell, if it is not interactive, exits. Otherwise, the value of parameter
+#   is substituted.
+#
+# Examples
+# ========
+#
+# Arrays:
+#
+#   ${some_array[@]:-}              # blank default value
+#   ${some_array[*]:-}              # blank default value
+#   ${some_array[0]:-}              # blank default value
+#   ${some_array[0]:-default_value} # default value: the string 'default_value'
+#
+# Postitional variables:
+#
+#   ${1:-alternative} # default value: the string 'alternative'
+#   ${2:-}            # blank default value
+#
+# With an error message:
+#
+#   ${1:?'error message'}  # exit with 'error message' if variable is unbound
+#
+# Short form: set -u
+set -o nounset
+
+# Exit immediately if a pipeline returns non-zero.
+#
+# NOTE: this has issues. When using read -rd '' with a heredoc, the exit
+# status is non-zero, even though there isn't an error, and this setting
+# then causes the script to exit. read -rd '' is synonymous to read -d $'\0',
+# which means read until it finds a NUL byte, but it reaches the EOF (end of
+# heredoc) without finding one and exits with a 1 status. Therefore, when
+# reading from heredocs with set -e, there are three potential solutions:
+#
+# Solution 1. set +e / set -e again:
+#
+# set +e
+# read -rd '' variable <<EOF
+# EOF
+# set -e
+#
+# Solution 2. <<EOF || true:
+#
+# read -rd '' variable <<EOF || true
+# EOF
+#
+# Solution 3. Don't use set -e or set -o errexit at all.
+#
+# More information:
+#
+# https://www.mail-archive.com/bug-bash@gnu.org/msg12170.html
+#
+# Short form: set -e
+set -o errexit
+
+# Return value of a pipeline is the value of the last (rightmost) command to
+# exit with a non-zero status, or zero if all commands in the pipeline exit
+# successfully.
+set -o pipefail
+
+# Set IFS to just newline and tab at the start
+#
+# http://www.dwheeler.com/essays/filenames-in-shell.html
+#
+# $DEFAULT_IFS and $SAFER_IFS
+#
+# $DEFAULT_IFS contains the default $IFS value in case it's needed, such as
+# when expanding an array and you want to separate elements by spaces.
+# $SAFER_IFS contains the preferred settings for the program, and setting it
+# separately makes it easier to switch between the two if needed.
+#
+# NOTE: also printing $DEFAULT_IFS to /dev/null to avoid shellcheck warnings
+# about the variable being unused.
+DEFAULT_IFS="$IFS"; printf "%s" "$DEFAULT_IFS" > /dev/null
+SAFER_IFS="$(printf '\n\t')"
+# Then set $IFS
+IFS="$SAFER_IFS"
+
+###############################################################################
 # Globals
 ###############################################################################
 
@@ -105,14 +207,95 @@ die() {
 ###############################################################################
 
 # Get raw options for any commands that expect them.
-raw_options=$*
+raw_options="$*"
 
-# Initialize command options and arguments arrays.
+# Steps:
 #
-# These contain any options and arguments that will be used by the commands.
-# Commands handle their own argument and option checks using the created arrays.
-command_options=()
-command_arguments=()
+# 1. set expected short options in `optstring` at beginning of the "Normalize
+#    Options" section,
+# 2. parse options in while loop in the "Parse Options" section.
+
+# Normalize Options ###########################################################
+
+# Source:
+#   https://github.com/e36freak/templates/blob/master/options
+
+# The first loop, even though it uses 'optstring', will NOT check if an
+# option that takes a required argument has the argument provided. That must
+# be done within the second loop and case statement, yourself. Its purpose
+# is solely to determine that -oARG is split into -o ARG, and not -o -A -R -G.
+
+# Set short options -----------------------------------------------------------
+
+# option string, for short options.
+#
+# Very much like getopts, expected short options should be appended to the
+# string here. Any option followed by a ':' takes a required argument.
+#
+# In this example, `-x` and `-h` are regular short options, while `o` is
+# assumed to have an argument and will be split if joined with the string,
+# meaning `-oARG` would be split to `-o ARG`.
+optstring=h
+
+# Normalize -------------------------------------------------------------------
+
+# iterate over options, breaking -ab into -a -b and --foo=bar into --foo bar
+# also turns -- into --endopts to avoid issues with things like '-o-', the '-'
+# should not indicate the end of options, but be an invalid option (or the
+# argument to the option, such as wget -qO-)
+unset options
+# while the number of arguments is greater than 0
+while (($#)); do
+  case $1 in
+    # if option is of type -ab
+    -[!-]?*)
+      # loop over each character starting with the second
+      for ((i=1; i<${#1}; i++)); do
+        # extract 1 character from position 'i'
+        c=${1:i:1}
+        # add current char to options
+        options+=("-$c")
+
+        # if option takes a required argument, and it's not the last char
+        # make the rest of the string its argument
+        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
+          options+=("${1:i+1}")
+          break
+        fi
+      done
+      ;;
+    # if option is of type --foo=bar, split on first '='
+    --?*=*) options+=("${1%%=*}" "${1#*=}");;
+    # end of options, stop breaking them up
+    --)
+      options+=(--endopts)
+      shift
+      options+=("$@")
+      break
+      ;;
+    # otherwise, nothing special
+    *) options+=("$1");;
+  esac
+
+  shift
+done
+# set new positional parameters to altered options. Set default to blank.
+set -- "${options[@]:-}"
+unset options
+
+# Parse Options ###############################################################
+
+# Initialize command_argv array
+#
+# This array contains all of the arguments that get passed along to each
+# command. This is essentially the same as the program arguments, minus those
+# that have been filtered out in the program option parsing loop. This array
+# is initialized with $0, which is the program's name.
+command_argv=("$0")
+# Initialize $cmd and $_use_debug, which can continue to be blank depending on
+# what the program needs.
+cmd=""
+_use_debug=0
 
 while [ $# -gt 0 ]; do
   opt="$1"
@@ -121,28 +304,33 @@ while [ $# -gt 0 ]; do
     -h|--help)
       cmd="help"
       ;;
-    --debug)
-      debug=1
+    --version)
+      cmd="version"
       ;;
-    -*|--*)
-      command_options+=("$opt")
+    --debug)
+      _use_debug=1
       ;;
     *)
       # The first non-option argument is assumed to be the command name.
       # All subsequent arguments are added to $command_arguments.
       if [[ -n $cmd ]]; then
-        command_arguments+=("$opt")
+        command_argv+=("$opt")
       else
-        cmd=$opt
+        cmd="$opt"
       fi
       ;;
   esac
 done
 
+# Set $command_parameters to $command_argv, minus the initial element, $0. This
+# provides an array that is equivalent to $* and $@ within each command
+# function, though the array is zero-indexed, which could lead to confusion.
+command_parameters=("${command_argv[@]:1}")
+
 _debug printf "\$cmd: %s\n" "$cmd"
-_debug printf "\$raw_options: %s\n" "$raw_options"
-_debug printf "\$command_options: %s\n" "${command_options[*]}"
-_debug printf "\$command_arguments: %s\n" "${command_arguments[*]}"
+_debug printf "\$raw_options (one per line):\n%s\n" "$raw_options"
+_debug printf "\$command_argv: %s\n" "${command_argv[*]}"
+_debug printf "\$command_parameters: %s\n" "${command_parameters[*]:-}"
 
 ###############################################################################
 # Environment
@@ -154,6 +342,55 @@ _debug printf "\$command_arguments: %s\n" "${command_arguments[*]}"
 _me=$(basename "$0")
 
 _debug printf "\$_me: %s\n" "$_me"
+
+###############################################################################
+# Load Commands
+###############################################################################
+
+# Initialize defined_commands array.
+defined_commands=()
+
+# _load_commands()
+#
+# Loads all of the commands sourced in the environment.
+#
+# Usage:
+#   _load_commands
+_load_commands() {
+
+  _debug printf "_load_commands(): entering...\n"
+  _debug printf "_load_commands() declare -F:\n%s\n" "$(declare -F)"
+
+  # declare is a bash built-in shell function that, when called with the '-F'
+  # option, displays all of the functions with the format
+  # `declare -f function_name`. These are then assigned as elements in the
+  # $function_list array.
+  local function_list=($(declare -F))
+
+  for c in "${function_list[@]}"
+  do
+    # Each element has the format `declare -f function_name`, so set the name
+    # to only the 'function_name' part of the string.
+    local function_name=$(printf "%s" "$c" | awk '{ print $3 }')
+
+    _debug printf "_load_commands() \$function_name: %s\n" "$function_name"
+
+    # Add the function name to the $defined_commands array unless it starts
+    # with an underscore or is one of the desc(), debug(), or die() functions,
+    # since these are treated as having 'private' visibility.
+    if ! ( [[ "$function_name" =~ ^_(.*)  ]] || \
+           [[ "$function_name" == "desc"  ]] || \
+           [[ "$function_name" == "debug" ]] || \
+           [[ "$function_name" == "die"   ]]
+    ); then
+      defined_commands+=("$function_name")
+    fi
+  done
+
+  _debug printf \
+    "commands() \$defined_commands:\n%s\n" \
+    "${defined_commands[*]:-}"
+}
 
 ###############################################################################
 # Main
@@ -168,22 +405,52 @@ _debug printf "\$_me: %s\n" "$_me"
 #
 # NOTE: must be called at end of program after all commands have been defined.
 _main() {
+  _debug printf "main(): entering...\n"
+  _debug printf "main() \$cmd (upon entering): %s\n" "$cmd"
+
   # If $cmd is blank, then set to help
   if [[ -z $cmd ]]; then
     cmd="help"
   fi
 
-  # Get the list of defined commands.
-  defined_commands=($(commands --raw))
+  # Load all of the commands.
+  _load_commands
 
-  # Run the command and pass the command arguments.
-  if ( _contains "$cmd" "${defined_commands[@]}" ); then
-    $cmd "${command_arguments[@]}"
+  # If the command is defined, run it, otherwise return an error.
+  if ( _contains "$cmd" "${defined_commands[*]:-}" ); then
+    # Pass all comment arguments to the program except for the first ($0).
+    $cmd "${command_parameters[@]:-}"
   else
-    printf "Unknown command: %s\n" "$cmd"
-    exit 1
+    _die printf "Unknown command: %s\n" "$cmd"
   fi
 }
+
+###############################################################################
+# Getters
+###############################################################################
+
+# _get_command_argv()
+#
+# Print the value of a command argument at the specified position. This is
+# simply an accessor for the command_argv array.
+#
+# Usage:
+#   $(_get_command_argv 1)
+_get_command_argv() {
+  local position="${1:-}"
+
+  if [[ -z "$position" ]]; then
+    _die printf "Error: _get_command_argv(): no value specified.\n"
+  else
+    printf \
+      "%s" \
+      "${command_argv[${position:-}]:-}" # return a blank if not present
+  fi
+}
+
+_debug printf \
+  "\$(_get_command_argv 1): %s\n" \
+  "$(_get_command_argv 1)"
 
 ###############################################################################
 # Utility Functions
@@ -216,26 +483,18 @@ _contains() {
   return 1
 }
 
-# _commnd_options_include()
-#
-# Takes a possible command option and determines whether it is included in
-# the command option list.
-#
-# Usage:
-#   _command_options_include "--an-option"
-_command_options_include() {
-  _contains "$1" "${command_options[@]}"
-}
-
-# _commnd_arguments_include()
+# _command_argv_includes()
 #
 # Takes a possible command argument and determines whether it is included in
 # the command argument list.
 #
+# This is a shortcut for simple cases where a command wants to check for the
+# presence of options quickly without parsing the options again.
+#
 # Usage:
-#   _command_arguments_include "an_argument"
-_command_arguments_include() {
-  _contains "$1" "${command_arguments[@]}"
+#   _command_argv_includes "an_argument"
+_command_argv_includes() {
+  _contains "$1" "${command_argv[*]}"
 }
 
 ###############################################################################
@@ -302,16 +561,32 @@ _print_desc() {
 # Default Commands
 ###############################################################################
 
+# Version #####################################################################
+
+desc version <<EOM
+Usage:
+  $_me ( version | --version )
+
+Description:
+  Display the current program version.
+
+  To save you the trouble, the current version is $_VERSION
+EOM
+version() {
+  printf "%s\n" "$_VERSION"
+}
+
 # Help ########################################################################
 
 desc help <<EOM
 Usage:
   $_me help [<command>]
 
-Display help information for $_me or a specified command
+Description:
+  Display help information for $_me or a specified command.
 EOM
 help() {
-  if [[ $# = 0 ]]; then
+  if [[ ${#command_argv[@]} = 1 ]]; then
     cat <<EOM
 
           _ _                        _
@@ -323,8 +598,16 @@ help() {
 
 Improved git subtrees.
 
+Version: $_VERSION
+
 Usage:
-  $_me command [<command-arguments>]
+  $_me command [--command-options] [<arguments>]
+  $_me -h | --help
+  $_me --version
+
+Options:
+  -h --help  Display this help information.
+  --version  Display version information.
 
 Help:
   $_me help [<command>]
@@ -343,26 +626,18 @@ desc commands <<EOM
 Usage:
   $_me commands [--raw]
 
-Display the list of available commands.
+Options:
+  --raw  Display the command list without formatting.
+
+Description:
+  Display the list of available commands.
 EOM
 commands() {
-  function_list=($(declare -F))
-  command_list=()
-  for c in "${function_list[@]}"
-  do
-    if ! ( [[ "$c" == "declare" ]] || \
-           [[ "$c" == "-f" ]] || \
-           [[ "$c" =~ ^_(.*) ]] || \
-           [[ "$c" == "desc" ]]
-    ); then
-      command_list+=("$c")
-    fi
-  done
-  if _contains "--raw" "${command_options[@]}"; then
-    printf "%s " "${command_list[@]}"
+  if _command_argv_includes "--raw"; then
+    printf "%s\n" "${defined_commands[@]}"
   else
     printf "Available commands:\n"
-    printf "  %s\n" "${command_list[@]}"
+    printf "  %s\n" "${defined_commands[@]}"
   fi
 }
 
@@ -370,17 +645,25 @@ commands() {
 # Commands
 # ========.....................................................................
 #
-# Example command group:
+# Example command group structure:
 #
 # desc example ""   - Optional. A short description for the command.
-# example() { : }   - The command called by the use.
+# example() { : }   - The command called by the user.
 #
 #
 # desc example <<EOM
-#   Example help text. Options specified with http://docopt.org/
+#   Usage:
+#     $_me example
+#
+#   Description:
+#     Print "Hello, World!"
+#
+#     For usage formatting conventions see:
+#     - http://docopt.org/
+#     - http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
 # EOM
 # example() {
-#   echo "Hello, World!"
+#   printf "Hello, World!\n"
 # }
 #
 ###############################################################################
